export type contactType = {
  iContactId: number;
  sFullName: string;
  sEmail: string;
  sPhoneMobile: string;
  sJobTitle: string;
  eCompany: number;
  sCompany: string;
  sPhoneBusiness: string;
  sActive: boolean;
  bEdit: boolean;
  bPrivate?: boolean;
  sArea: number;
  sCity?: string;
  sAddress?: string;
  sComment: string;
};

export const contacts_lst: contactType[] = [
  {
    iContactId: 1,
    sFullName: 'John Carter',
    sEmail: 'john.carter@example.com',
    sPhoneMobile: '+1 (555) 123-4567',
    sJobTitle: 'Sales Executive',
    eCompany: 1,
    sCompany: 'TechCorp Inc.',
    sPhoneBusiness: '+1 (555) 987-6543',
    sActive: true,
    bEdit: true,
    bPrivate: false,
    sArea: 201,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'This is a sample contact for testing purposes. Please do not delete.',
  },
  {
    iContactId: 2,
    sFullName: 'Emily Parker',
    sEmail: 'emily.parker@example.com',
    sPhoneMobile: '+44 7890 123456',
    sJobTitle: 'Marketing Manager',
    eCompany: 2,
    sCompany: 'Global Ads Ltd.',
    sPhoneBusiness: '+44 20 7946 0958',
    sActive: true,
    bEdit: true,
    bPrivate: false,
    sArea: 201,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'This contact is used for marketing campaigns and outreach.',
  },
  {
    iContactId: 3,
    sFullName: 'Alex Chen',
    sEmail: 'alex.chen@example.com',
    sPhoneMobile: '+86 138 0013 8000',
    sJobTitle: 'Senior Software Engineer',
    eCompany: 3,
    sCompany: 'ByteDynamics',
    sPhoneBusiness: '+86 10 5678 1234',
    sActive: false,
    bEdit: true,
    bPrivate: false,
    sArea: 202,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Alex is a key member of the development team, focusing on backend systems.',
  },
  {
    iContactId: 4,
    sFullName: 'Maria Gonzalez',
    sEmail: 'maria.g@example.com',
    sPhoneMobile: '+52 55 1234 5678',
    sJobTitle: 'HR Director',
    eCompany: 4,
    sCompany: 'PeopleFirst Solutions',
    sPhoneBusiness: '+52 55 9876 5432',
    sActive: true,
    bEdit: true,
    bPrivate: false,
    sArea: 204,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Maria oversees all HR operations and employee relations at PeopleFirst Solutions.',
  },
  {
    iContactId: 5,
    sFullName: 'David Wilson',
    sEmail: 'd.wilson@example.com',
    sPhoneMobile: '+1 (212) 555-0199',
    sJobTitle: 'Financial Analyst',
    eCompany: 5,
    sCompany: 'Capital Investments',
    sPhoneBusiness: '+1 (212) 555-0187',
    sActive: true,
    bEdit: true,
    bPrivate: false,
    sArea: 203,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'David provides financial insights and analysis to support business decisions.',
  },
  {
    iContactId: 6,
    sFullName: 'Sarah Johnson',
    sEmail: 's.johnson@example.com',
    sPhoneMobile: '+61 412 345 678',
    sJobTitle: 'Product Manager',
    eCompany: 6,
    sCompany: 'InnovateTech',
    sPhoneBusiness: '+61 2 9876 5432',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 203,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 7,
    sFullName: 'Michael Brown',
    sEmail: 'michael.b@example.com',
    sPhoneMobile: '+1 (415) 555-0123',
    sJobTitle: 'UX Designer',
    eCompany: 7,
    sCompany: 'Digital Creations',
    sPhoneBusiness: '+1 (415) 555-0198',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 202,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 8,
    sFullName: 'Lisa Wong',
    sEmail: 'lisa.wong@example.com',
    sPhoneMobile: '+65 8123 4567',
    sJobTitle: 'Operations Manager',
    eCompany: 8,
    sCompany: 'Asia Pacific Logistics',
    sPhoneBusiness: '+65 6321 9876',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 203,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 9,
    sFullName: 'Robert Taylor',
    sEmail: 'robert.t@example.com',
    sPhoneMobile: '+44 7700 900123',
    sJobTitle: 'IT Consultant',
    eCompany: 9,
    sCompany: 'TechSolutions UK',
    sPhoneBusiness: '+44 20 7123 4567',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 202,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 10,
    sFullName: 'Anna Kowalski',
    sEmail: 'anna.k@example.com',
    sPhoneMobile: '+48 600 123 456',
    sJobTitle: 'Customer Support Lead',
    eCompany: 10,
    sCompany: 'EuroCustomer Care',
    sPhoneBusiness: '+48 22 598 7654',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 201,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 11,
    sFullName: 'James Miller',
    sEmail: 'james.m@example.com',
    sPhoneMobile: '+1 (310) 555-0167',
    sJobTitle: 'Business Development',
    eCompany: 11,
    sCompany: 'Growth Partners',
    sPhoneBusiness: '+1 (310) 555-0176',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 201,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 12,
    sFullName: 'Sophia Martinez',
    sEmail: 's.martinez@example.com',
    sPhoneMobile: '+34 612 345 678',
    sJobTitle: 'Content Strategist',
    eCompany: 12,
    sCompany: 'Creative Minds Media',
    sPhoneBusiness: '+34 91 876 5432',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 202,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 13,
    sFullName: 'Daniel Kim',
    sEmail: 'daniel.kim@example.com',
    sPhoneMobile: '+82 10-1234-5678',
    sJobTitle: 'Data Scientist',
    eCompany: 13,
    sCompany: 'AI Innovations',
    sPhoneBusiness: '+82 2 5678 1234',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 203,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 14,
    sFullName: 'Olivia Smith',
    sEmail: 'olivia.s@example.com',
    sPhoneMobile: '+1 (647) 555-0124',
    sJobTitle: 'Recruiter',
    eCompany: 14,
    sCompany: 'TalentFinders',
    sPhoneBusiness: '+1 (647) 555-0135',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 203,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },

  {
    iContactId: 15,
    sFullName: 'Thomas Johnson',
    sEmail: 'thomas.j@example.com',
    sPhoneMobile: '+46 70 123 45 67',
    sJobTitle: 'Sales Director',
    eCompany: 15,
    sCompany: 'Nordic Sales Group',
    sPhoneBusiness: '+46 8 765 43 21',
    bEdit: false,
    sActive: true,
    bPrivate: false,
    sArea: 202,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },

  {
    iContactId: 18,
    sFullName: 'Ava Thompson',
    sEmail: 'ava.t@example.com',
    sPhoneMobile: '+1 (778) 555-0178',
    sJobTitle: 'Graphic Designer',
    eCompany: 18,
    sCompany: 'Visual Arts Studio',
    sPhoneBusiness: '+1 (778) 555-0167',
    sActive: true,
    bEdit: false,
    bPrivate: false,
    sArea: 202,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
  {
    iContactId: 19,
    sFullName: 'Noah Anderson',
    sEmail: 'noah.a@example.com',
    sPhoneMobile: '+47 412 34 567',
    sJobTitle: 'Supply Chain Manager',
    eCompany: 19,
    sCompany: 'Nordic Goods',
    sPhoneBusiness: '+47 22 33 44 55',
    bEdit: false,
    sActive: true,
    bPrivate: false,
    sArea: 203,
    sCity: 'Manama',
    sAddress: '123 Tech Street, Suite 100, Manama, Bahrain',
    sComment: 'Sarah leads product development and strategy at InnovateTech.',
  },
];
