export type customerType = {
  iCustomerId: number;
  iCategoryId: number;
  iAreaId: number;
  iUserAppManagerId: number;
  iStatusId: number;
  sLocation: string;
  bEdit: boolean;
  sContact: string;
  dtCreated: Date;
  dtUpdated: Date;
  dtDescriptionUpdated: Date;
  sCustomerId: string;
  sCustomer: string;
  sNextStep: string;
  sStatus: string;
  sContactCount?: number; // Optional, can be undefined
  sOppsCount?: number; // Optional, can be undefined
  sCategory?: string; // Optional, can be undefined
  lstBTs?: string[]; // Optional, can be undefined
};

export const lst_customers = [
  {
    iCustomerId: 1,
    iCategoryId: 101,
    iAreaId: 201,
    iUserAppManagerId: 301,
    iStatusId: 1,
    sLocation: 'New York',
    bEdit: false,
    sContact: 'John Smith',
    dtCreated: new Date('2023-01-15'),
    dtUpdated: new Date('2023-06-20'),
    dtDescriptionUpdated: new Date('2023-06-18'),
    sCustomerId: 'CUST001',
    sCustomer: 'ABC Corporation',
    sNextStep: 'Follow-up meeting',
    sStatus: 'Active',
    sContactCount: 223,
    sOppsCount: 15,
    sCategory: 'A',
    lstBTs: ['BT123', 'BT456'],
  },
  {
    iCustomerId: 2,
    iCategoryId: 102,
    iAreaId: 202,
    iUserAppManagerId: 302,
    iStatusId: 2,
    sLocation: 'Los Angeles',
    bEdit: true,
    sContact: 'Sarah Johnson',
    dtCreated: new Date('2023-02-10'),
    dtUpdated: new Date('2023-06-15'),
    dtDescriptionUpdated: new Date('2023-06-10'),
    sCustomerId: 'CUST002',
    sCustomer: 'XYZ Enterprises',
    sNextStep: 'Proposal submission',
    sStatus: 'Pending',
    sCategory: 'A',
    lstBTs: ['BT789', 'BT101'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 3,
    iCategoryId: 103,
    iAreaId: 203,
    iUserAppManagerId: 303,
    iStatusId: 3,
    sLocation: 'Chicago',
    bEdit: false,
    sContact: 'Michael Brown',
    dtCreated: new Date('2023-03-05'),
    dtUpdated: new Date('2023-06-12'),
    dtDescriptionUpdated: new Date('2023-06-08'),
    sCustomerId: 'CUST003',
    sCustomer: 'Global Tech',
    sNextStep: 'Contract signing',
    sStatus: 'Completed',
    sCategory: 'A',
    lstBTs: ['BT112', 'BT131'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 4,
    iCategoryId: 101,
    iAreaId: 204,
    iUserAppManagerId: 304,
    iStatusId: 1,
    sLocation: 'Houston',
    bEdit: false,
    sContact: 'Emily Davis',
    dtCreated: new Date('2023-04-18'),
    dtUpdated: new Date('2023-06-10'),
    dtDescriptionUpdated: new Date('2023-06-05'),
    sCustomerId: 'CUST004',
    sCustomer: 'Sunrise Solutions',
    sNextStep: 'Product demo',
    sStatus: 'Active',
    sCategory: 'B',
    lstBTs: ['BT415', 'BT161'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 5,
    iCategoryId: 102,
    iAreaId: 205,
    iUserAppManagerId: 305,
    iStatusId: 2,
    sLocation: 'Phoenix',
    bEdit: true,
    sContact: 'David Wilson',
    dtCreated: new Date('2023-05-22'),
    dtUpdated: new Date('2023-06-08'),
    dtDescriptionUpdated: new Date('2023-06-03'),
    sCustomerId: 'CUST005',
    sCustomer: 'Oceanic Services',
    sNextStep: 'Requirements gathering',
    sStatus: 'Pending',
    sCategory: 'B',
    lstBTs: ['BT718', 'BT192'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 6,
    iCategoryId: 103,
    iAreaId: 201,
    iUserAppManagerId: 306,
    iStatusId: 3,
    sLocation: 'Philadelphia',
    bEdit: false,
    sContact: 'Jessica Taylor',
    dtCreated: new Date('2023-01-30'),
    dtUpdated: new Date('2023-06-05'),
    dtDescriptionUpdated: new Date('2023-06-01'),
    sCustomerId: 'CUST006',
    sCustomer: 'Mountain View Inc',
    sNextStep: 'Final approval',
    sStatus: 'Completed',
    sCategory: 'B',
    lstBTs: ['BT021', 'BT224'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 7,
    iCategoryId: 101,
    iAreaId: 202,
    iUserAppManagerId: 307,
    iStatusId: 1,
    sLocation: 'San Antonio',
    bEdit: false,
    sContact: 'Robert Anderson',
    dtCreated: new Date('2023-02-14'),
    dtUpdated: new Date('2023-06-03'),
    dtDescriptionUpdated: new Date('2023-05-30'),
    sCustomerId: 'CUST007',
    sCustomer: 'Silver Linings LLC',
    sNextStep: 'Implementation',
    sStatus: 'Active',
    sCategory: 'B',
    lstBTs: ['BT325', 'BT426'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 8,
    iCategoryId: 102,
    iAreaId: 203,
    iUserAppManagerId: 308,
    iStatusId: 2,
    sLocation: 'San Diego',
    bEdit: true,
    sContact: 'Jennifer Martinez',
    dtCreated: new Date('2023-03-08'),
    dtUpdated: new Date('2023-06-01'),
    dtDescriptionUpdated: new Date('2023-05-28'),
    sCustomerId: 'CUST008',
    sCustomer: 'Golden Gate Partners',
    sNextStep: 'Review meeting',
    sStatus: 'Pending',
    sCategory: 'B',
    lstBTs: ['BT527', 'BT628'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 9,
    iCategoryId: 103,
    iAreaId: 204,
    iUserAppManagerId: 309,
    iStatusId: 3,
    sLocation: 'Dallas',
    bEdit: false,
    sContact: 'Thomas Clark',
    dtCreated: new Date('2023-04-12'),
    dtUpdated: new Date('2023-05-30'),
    dtDescriptionUpdated: new Date('2023-05-25'),
    sCustomerId: 'CUST009',
    sCustomer: 'Lone Star Systems',
    sNextStep: 'Project closure',
    sStatus: 'Completed',
    sCategory: 'B',
    lstBTs: ['BT729', 'BT830'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 10,
    iCategoryId: 101,
    iAreaId: 205,
    iUserAppManagerId: 310,
    iStatusId: 1,
    sLocation: 'San Jose',
    bEdit: false,
    sContact: 'Lisa Rodriguez',
    dtCreated: new Date('2023-05-05'),
    dtUpdated: new Date('2023-05-28'),
    dtDescriptionUpdated: new Date('2023-05-23'),
    sCustomerId: 'CUST010',
    sCustomer: 'Pacific Innovations',
    sNextStep: 'Training session',
    sStatus: 'Active',
    sCategory: 'B',
    lstBTs: ['BT931', 'BT032'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 11,
    iCategoryId: 102,
    iAreaId: 201,
    iUserAppManagerId: 311,
    iStatusId: 2,
    sLocation: 'Austin',
    bEdit: true,
    sContact: 'Daniel Lewis',
    dtCreated: new Date('2023-01-20'),
    dtUpdated: new Date('2023-05-25'),
    dtDescriptionUpdated: new Date('2023-05-20'),
    sCustomerId: 'CUST011',
    sCustomer: 'Texas Digital',
    sNextStep: 'Budget approval',
    sStatus: 'Pending',
    sCategory: 'B',
    lstBTs: ['BT133', 'BT234'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 12,
    iCategoryId: 103,
    iAreaId: 202,
    iUserAppManagerId: 312,
    iStatusId: 3,
    sLocation: 'Jacksonville',
    bEdit: false,
    sContact: 'Nancy Walker',
    dtCreated: new Date('2023-02-05'),
    dtUpdated: new Date('2023-05-23'),
    dtDescriptionUpdated: new Date('2023-05-18'),
    sCustomerId: 'CUST012',
    sCustomer: 'Sunshine Technologies',
    sNextStep: 'Delivery confirmation',
    sStatus: 'Completed',
    sCategory: 'B',
    lstBTs: ['BT335', 'BT436'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 13,
    iCategoryId: 101,
    iAreaId: 203,
    iUserAppManagerId: 313,
    iStatusId: 1,
    sLocation: 'Fort Worth',
    bEdit: false,
    sContact: 'Kevin Hall',
    dtCreated: new Date('2023-03-15'),
    dtUpdated: new Date('2023-05-20'),
    dtDescriptionUpdated: new Date('2023-05-15'),
    sCustomerId: 'CUST013',
    sCustomer: 'North Star Solutions',
    sNextStep: 'Quarterly review',
    sStatus: 'Active',
    sCategory: 'B',
    lstBTs: ['BT537', 'BT638'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 14,
    iCategoryId: 102,
    iAreaId: 204,
    iUserAppManagerId: 314,
    iStatusId: 2,
    sLocation: 'Columbus',
    bEdit: true,
    sContact: 'Amanda Young',
    dtCreated: new Date('2023-04-10'),
    dtUpdated: new Date('2023-05-18'),
    dtDescriptionUpdated: new Date('2023-05-13'),
    sCustomerId: 'CUST014',
    sCustomer: 'Midwest Manufacturing',
    sNextStep: 'Vendor selection',
    sStatus: 'Pending',
    sCategory: 'C',
    lstBTs: ['BT739', 'BT840'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 15,
    iCategoryId: 103,
    iAreaId: 205,
    iUserAppManagerId: 315,
    iStatusId: 3,
    sLocation: 'Charlotte',
    bEdit: false,
    sContact: 'Steven Allen',
    dtCreated: new Date('2023-05-01'),
    dtUpdated: new Date('2023-05-15'),
    dtDescriptionUpdated: new Date('2023-05-10'),
    sCustomerId: 'CUST015',
    sCustomer: 'Carolina Networks',
    sNextStep: 'Final payment',
    sStatus: 'Completed',
    sCategory: 'C',
    lstBTs: ['BT941', 'BT042'],
    sContactCount: 223,
    sOppsCount: 15,
  },
  {
    iCustomerId: 16,
    iCategoryId: 101,
    iAreaId: 201,
    iUserAppManagerId: 316,
    iStatusId: 1,
    sLocation: 'San Francisco',
    bEdit: false,
    sContact: 'Michelle King',
    dtCreated: new Date('2023-01-25'),
    dtUpdated: new Date('2023-05-13'),
    dtDescriptionUpdated: new Date('2023-05-08'),
    sCustomerId: 'CUST016',
    sCustomer: 'Bay Area Consulting',
    sNextStep: 'Strategy session',
    sStatus: 'Active',
    sCategory: 'C',
    lstBTs: ['BT143', 'BT244'],
    sContactCount: 223,
    sOppsCount: 15,
  },
];
export const lst_customers_status = [
  { iStatusId: 1, sStatus: 'Active' },
  { iStatusId: 2, sStatus: 'Pending' },
  { iStatusId: 3, sStatus: 'Completed' },
];
export const lst_customers_categories = [
  { iCategoryId: 101, sCategory: 'A' },
  { iCategoryId: 102, sCategory: 'B' },
  { iCategoryId: 103, sCategory: 'C' },
];
export const lst_customers_areas = [
  { iAreaId: 201, sArea: 'North America' },
  { iAreaId: 202, sArea: 'Europe' },
  { iAreaId: 203, sArea: 'Asia' },
  { iAreaId: 204, sArea: 'South America' },
  { iAreaId: 205, sArea: 'Africa' },
];
export const lst_customers_industries = [
  { industryId: 1, sIndustry: 'Technology && fsfsd' },
  { industryId: 2, sIndustry: 'Finance && food' },
  { industryId: 3, sIndustry: 'Healthcare' },
  { industryId: 4, sIndustry: 'Retail' },
  { industryId: 5, sIndustry: 'Manufacturing' },
];
export const lst_customers_users = [
  { iUserAppManagerId: 301, sUserAppManager: 'Alice Johnson' },
  { iUserAppManagerId: 302, sUserAppManager: 'Bob Smith' },
  { iUserAppManagerId: 303, sUserAppManager: 'Charlie Brown' },
  { iUserAppManagerId: 304, sUserAppManager: 'Diana Prince' },
  { iUserAppManagerId: 305, sUserAppManager: 'Ethan Hunt' },
  { iUserAppManagerId: 306, sUserAppManager: 'Fiona Gallagher' },
  { iUserAppManagerId: 307, sUserAppManager: 'George Costanza' },
  { iUserAppManagerId: 308, sUserAppManager: 'Hannah Montana' },
  { iUserAppManagerId: 309, sUserAppManager: 'Ian Malcolm' },
];
export const comments = [
  { id: '1', sComment: 'This is a comment', iUser: 'User1', date: '2024-03-20' },
  { id: '2', sComment: 'This is another comment', iUser: 'User2', date: '2024-03-21' },
  { id: '3', sComment: 'Yet another comment', iUser: 'User3', date: '2024-03-22' },
  { id: '4', sComment: 'This is a comment', iUser: 'User4', date: '2024-03-23' },
  { id: '5', sComment: 'This is a comment', iUser: 'User5', date: '2024-03-24' },
  { id: '6', sComment: 'This is a comment', iUser: 'User6', date: '2024-03-25' },
  { id: '7', sComment: 'This is a comment', iUser: 'User7', date: '2024-03-26' },
  { id: '8', sComment: 'This is a comment', iUser: 'User8', date: '2024-03-27' },
  { id: '9', sComment: 'This is a comment', iUser: 'User9', date: '2024-03-28' },
  { id: '10', sComment: 'This is a comment', iUser: 'User10', date: '2024-03-29' },
];
